version: '3'
services:
  v2ray:
    container_name: v2ray
    image: v2ray/official
    ports:
      - 127.0.0.1:1080:1080
    volumes:
      - ./v2ray:/etc/v2ray
    command: v2ray -config=/etc/v2ray/config.json
  pac-httpd:
    container_name: pac-httpd
    environment:
      restart: always
    image: busybox
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./pac:/tmp
    command: httpd -v -f -h /tmp
